outputfolder:
  postselector_results: { 
    "2022": "/eos/home-a/acagnott/DarkMatter/nosynch/run2022_test/",
    "2022EE": "/eos/home-a/acagnott/DarkMatter/nosynch/run2022EE_test/",
    "2023": "/eos/home-a/acagnott/DarkMatter/nosynch/run2023_test/",
    "2023postBPix": "/eos/home-a/acagnott/DarkMatter/nosynch/run2023postBPix_test/",
    }

dict_samples:
  2022: "../samples/dict_samples_2022.json"
  2023: "../samples/dict_samples_2023.json"

